[config]
schemaVersion = "0.0.1"

[package]
namespace = "LethalCompanyModding"
name = "HostFurnitureReset"
versionNumber = "1.0.0"
description = "Resets furniture positions for the host"
websiteUrl = "https://github.com/LethalCompanyModding/HostFurnitureReset"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"


[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./build"

[[build.copy]]
source = "../bin/LCM/HostFurnitureReset.dll"
target = "/plugins/HostFurnitureReset/"

[[build.copy]]
source = "../license"
target = "/"

[general]
repository = "https://thunderstore.io"

[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "mods" ]


